import { writeFile } from "node:fs/promises";
import { seedDatabase } from "../lib/data.ts";
import type { Database, DatabaseResult, DatabaseStatement } from "../lib/postgres-db.ts";

type RecordedStatement = DatabaseStatement & {
  query: string;
  values: unknown[];
};

class RecorderStatement implements RecordedStatement {
  readonly query: string;
  readonly values: unknown[];

  constructor(query: string, values: unknown[] = []) {
    this.query = query;
    this.values = values;
  }

  bind(...values: unknown[]) {
    return new RecorderStatement(this.query, values);
  }

  async first<T>() {
    return { available: true } as T;
  }

  async all<T>() {
    return { results: [] as T[] };
  }

  async run() {
    return { success: true as const, meta: { changes: 0 } };
  }
}

const batches: RecordedStatement[][] = [];
const recorder: Database = {
  prepare(query) {
    return new RecorderStatement(query);
  },
  async batch(statements) {
    batches.push(statements as RecordedStatement[]);
    return statements.map(() => ({ results: [], success: true, meta: { changes: 0 } })) as DatabaseResult[];
  },
};

function literal(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error(`Cannot encode non-finite number: ${value}`);
    return String(value);
  }
  if (typeof value === "boolean") return value ? "true" : "false";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function render(statement: RecordedStatement): string {
  let parameter = 0;
  const query = statement.query.replace(/\?/g, () => {
    if (parameter >= statement.values.length) throw new Error(`Missing seed value for: ${statement.query}`);
    return literal(statement.values[parameter++]);
  });
  if (parameter !== statement.values.length) throw new Error(`Unused seed values for: ${statement.query}`);
  return `${query.trim().replace(/;$/, "")};`;
}

await seedDatabase(recorder);
if (batches.length !== 1) throw new Error(`Expected one atomic seed batch, received ${batches.length}.`);

const output = [
  "-- Generated by: npm run db:seed:generate",
  "-- The application uses the same seed path on first start, so this file is safe to replay.",
  "begin;",
  ...batches[0].map(render),
  "commit;",
  "",
].join("\n");

await writeFile(new URL("./seed.sql", import.meta.url), output, "utf8");
