const SUPPLIER_ID = "SUP-CSHACK";
const PRICE_CHECKED_ON = "2026-08-12";

type CatalogueMaterialInput = {
  id: string;
  name: string;
  category: "WAX" | "FRAGRANCE" | "WICKS" | "COLOURANTS" | "CONTAINERS" | "PACKAGING" | "OTHER";
  supplierSku: string;
  unit: "g" | "units";
  packSizeMilli: number;
  exVatPence: number;
  incVatPence: number;
  supplierProductUrl: string;
};

function catalogueMaterial(input: CatalogueMaterialInput) {
  const purchasePriceMicros = input.exVatPence * 10_000;
  const unitCostMicros = Math.round((purchasePriceMicros * 1_000) / input.packSizeMilli);

  return {
    id: input.id,
    name: input.name,
    category: input.category,
    supplierId: SUPPLIER_ID,
    supplierSku: input.supplierSku,
    unit: input.unit,
    packSizeMilli: input.packSizeMilli,
    purchasePriceMicros,
    purchasePriceIncVatMicros: input.incVatPence * 10_000,
    unitCostMicros,
    lastPurchaseUnitCostMicros: unitCostMicros,
    minimumStockMilli: 0,
    reorderPointMilli: 0,
    preferredOrderQtyMilli: input.packSizeMilli,
    leadTimeDays: 7,
    location: null,
    active: true,
    supplierProductUrl: input.supplierProductUrl,
    priceCheckedOn: PRICE_CHECKED_ON,
  };
}

export const supplierCatalogue = {
  source: {
    supplierId: SUPPLIER_ID,
    priceCheckedOn: PRICE_CHECKED_ON,
    vatBps: 2_000,
    selectionBasis: "UK B2B range, transparent ex-VAT and inc-VAT pricing, product documentation and UK fulfilment",
  },
  supplier: {
    id: SUPPLIER_ID,
    name: "Candle Shack Ltd",
    contactName: "Customer Support",
    email: "support@candle-shack.co.uk",
    phone: "+44 1324 238032",
    website: "https://candle-shack.co.uk/",
    address: "Unit A, West Carron Works, Stenhouse Road, Carron, Stirlingshire, FK2 8DR",
    leadTimeDays: 7,
    minimumOrderPence: 0,
    paymentTerms: null,
    materialsSupplied: "Wax, fragrance oils, wicks, vessels, lids, dyes, labels and packaging",
    active: true,
    notes: "Live UK supplier catalogue; prices checked against the supplier product pages on 12 August 2026.",
  },
  materials: [
    catalogueMaterial({
      id: "MAT-CS-001",
      name: "EU Golden Wax 464 Soy Wax — 800g",
      category: "WAX",
      supplierSku: "WAX00481",
      unit: "g",
      packSizeMilli: 800_000,
      exVatPence: 437,
      incVatPence: 524,
      supplierProductUrl: "https://candle-shack.co.uk/products/european-golden-wax-464",
    }),
    catalogueMaterial({
      id: "MAT-CS-002",
      name: "EcoSystem RCX Rapeseed & Coconut Wax — 800g",
      category: "WAX",
      supplierSku: "WAX00371",
      unit: "g",
      packSizeMilli: 800_000,
      exVatPence: 519,
      incVatPence: 623,
      supplierProductUrl: "https://candle-shack.co.uk/products/ecosystem-rcx-wax",
    }),
    catalogueMaterial({
      id: "MAT-CS-003",
      name: "Dark Honey & Tobacco Fragrance Oil — 500g",
      category: "FRAGRANCE",
      supplierSku: "FRAG1763",
      unit: "g",
      packSizeMilli: 500_000,
      exVatPence: 3_419,
      incVatPence: 4_103,
      supplierProductUrl: "https://candle-shack.co.uk/products/dark-honey-tobacco",
    }),
    catalogueMaterial({
      id: "MAT-CS-004",
      name: "Black Plum & Rhubarb Fragrance Oil — 500g",
      category: "FRAGRANCE",
      supplierSku: "FRAG0713",
      unit: "g",
      packSizeMilli: 500_000,
      exVatPence: 3_363,
      incVatPence: 4_036,
      supplierProductUrl: "https://candle-shack.co.uk/products/black-plum-rhubarb",
    }),
    catalogueMaterial({
      id: "MAT-CS-005",
      name: "Warm Woods & Cashmere Fragrance Oil — 500g",
      category: "FRAGRANCE",
      supplierSku: "FRAG4473",
      unit: "g",
      packSizeMilli: 500_000,
      exVatPence: 3_586,
      incVatPence: 4_303,
      supplierProductUrl: "https://candle-shack.co.uk/products/warm-woods-cashmere-fragrance-oil",
    }),
    catalogueMaterial({
      id: "MAT-CS-006",
      name: "CL12 Pre-waxed Wick — pack of 100",
      category: "WICKS",
      supplierSku: "WICK2057",
      unit: "units",
      packSizeMilli: 100_000,
      exVatPence: 722,
      incVatPence: 866,
      supplierProductUrl: "https://candle-shack.co.uk/products/cl12-wick",
    }),
    catalogueMaterial({
      id: "MAT-CS-007",
      name: "Stabilo 14 Pre-waxed Wick — pack of 100",
      category: "WICKS",
      supplierSku: "WICK3107",
      unit: "units",
      packSizeMilli: 100_000,
      exVatPence: 722,
      incVatPence: 866,
      supplierProductUrl: "https://candle-shack.co.uk/products/stabilo-14-wick",
    }),
    catalogueMaterial({
      id: "MAT-CS-008",
      name: "20mm Adhesive Wick Pads — pack of 100",
      category: "WICKS",
      supplierSku: "WICK0042",
      unit: "units",
      packSizeMilli: 100_000,
      exVatPence: 371,
      incVatPence: 445,
      supplierProductUrl: "https://candle-shack.co.uk/products/20mm-adhesive-wick-pads",
    }),
    catalogueMaterial({
      id: "MAT-CS-009",
      name: "20cl Lotti Clear Candle Jar — pack of 6",
      category: "CONTAINERS",
      supplierSku: "GLAS0200-6",
      unit: "units",
      packSizeMilli: 6_000,
      exVatPence: 530,
      incVatPence: 636,
      supplierProductUrl: "https://candle-shack.co.uk/products/20cl-glass-clear",
    }),
    catalogueMaterial({
      id: "MAT-CS-010",
      name: "20cl Silver Candle Tin — pack of 6",
      category: "CONTAINERS",
      supplierSku: "TIN00011-6",
      unit: "units",
      packSizeMilli: 6_000,
      exVatPence: 639,
      incVatPence: 767,
      supplierProductUrl: "https://candle-shack.co.uk/products/20cl-candle-tin-new-size-silver",
    }),
    catalogueMaterial({
      id: "MAT-CS-011",
      name: "Natural Wooden Lid for 20cl Lotti — pack of 6",
      category: "CONTAINERS",
      supplierSku: "LID00105-6",
      unit: "units",
      packSizeMilli: 6_000,
      exVatPence: 482,
      incVatPence: 578,
      supplierProductUrl: "https://candle-shack.co.uk/products/wooden-lid-natural-for-20cl-karen",
    }),
    catalogueMaterial({
      id: "MAT-CS-012",
      name: "White Simplicity Candle Box Size 2 — pack of 6",
      category: "PACKAGING",
      supplierSku: "BOX00007-6",
      unit: "units",
      packSizeMilli: 6_000,
      exVatPence: 357,
      incVatPence: 428,
      supplierProductUrl: "https://candle-shack.co.uk/products/folding-box-for-20cl-jars-white",
    }),
    catalogueMaterial({
      id: "MAT-CS-013",
      name: "Bekro Black Candle Dye 6000/01 — 10g",
      category: "COLOURANTS",
      supplierSku: "DYE00094",
      unit: "g",
      packSizeMilli: 10_000,
      exVatPence: 189,
      incVatPence: 227,
      supplierProductUrl: "https://candle-shack.co.uk/products/bekro-dye-6000-01-black-10g",
    }),
    catalogueMaterial({
      id: "MAT-CS-014",
      name: "50mm White Candle Safety Label — pack of 100",
      category: "PACKAGING",
      supplierSku: "LABL0052",
      unit: "units",
      packSizeMilli: 100_000,
      exVatPence: 478,
      incVatPence: 574,
      supplierProductUrl: "https://candle-shack.co.uk/products/candle-safety-label-50mm-white-paper",
    }),
  ],
} as const;
