create table public.app_meta (
  key text primary key,
  value text not null,
  updated_at text not null default (current_timestamp::text)
);

create table public.settings (
  workspace_id text primary key,
  business_name text not null,
  currency_code text not null default 'GBP',
  vat_bps integer not null default 2000,
  waste_bps integer not null default 300,
  labour_rate_pence_per_hour bigint not null default 1450,
  target_margin_bps integer not null default 6500,
  source_filename text not null,
  imported_on text not null,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table public.suppliers (
  id text primary key,
  name text not null,
  contact_name text,
  email text,
  phone text,
  website text,
  address text,
  lead_time_days integer not null default 0,
  minimum_order_pence bigint not null default 0,
  payment_terms text,
  materials_supplied text,
  active smallint not null default 1 check (active in (0, 1)),
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table public.materials (
  id text primary key,
  name text not null,
  category text not null,
  supplier_id text references public.suppliers(id) on delete set null,
  supplier_sku text,
  unit text not null,
  pack_size_milli bigint not null,
  purchase_price_micros bigint not null,
  purchase_price_inc_vat_micros bigint,
  unit_cost_micros bigint not null,
  last_purchase_unit_cost_micros bigint not null,
  minimum_stock_milli bigint not null default 0,
  reorder_point_milli bigint not null default 0,
  preferred_order_qty_milli bigint not null default 0,
  lead_time_days integer not null default 0,
  location text,
  supplier_product_url text,
  price_checked_on text,
  active smallint not null default 1 check (active in (0, 1)),
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create index materials_supplier_idx on public.materials(supplier_id);
create index materials_category_idx on public.materials(category);

create table public.products (
  id text primary key,
  sku text not null unique,
  name text not null,
  collection text not null,
  candle_type text not null,
  container_size_ml integer not null,
  wax_weight_milli bigint not null,
  fragrance text not null,
  fragrance_bps integer not null,
  wick_type text not null,
  colour text not null,
  selling_price_pence bigint not null,
  target_stock_milli bigint not null default 0,
  production_trigger_milli bigint not null default 0,
  direct_labour_minutes_milli bigint not null default 0,
  packaging_labour_minutes_milli bigint not null default 0,
  energy_cost_micros bigint not null default 0,
  overhead_cost_micros bigint not null default 0,
  selling_cost_micros bigint not null default 0,
  active smallint not null default 1 check (active in (0, 1)),
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table public.bom_items (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  material_id text not null references public.materials(id) on delete restrict,
  quantity_milli bigint not null,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text),
  constraint bom_product_material_uidx unique (product_id, material_id)
);

create index bom_material_idx on public.bom_items(material_id);

create table public.production_plans (
  id text primary key,
  name text not null,
  status text not null default 'scenario',
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create table public.production_plan_lines (
  id bigint generated by default as identity primary key,
  plan_id text not null references public.production_plans(id) on delete cascade,
  line_no integer not null,
  product_id text not null references public.products(id) on delete restrict,
  desired_qty_milli bigint not null,
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text),
  constraint plan_line_uidx unique (plan_id, line_no)
);

create table public.purchase_orders (
  po_number text primary key,
  order_date text not null,
  supplier_id text not null references public.suppliers(id) on delete restrict,
  status text not null,
  expected_date text,
  actual_date text,
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create index po_supplier_idx on public.purchase_orders(supplier_id);
create index po_status_idx on public.purchase_orders(status);

create table public.purchase_order_lines (
  id bigint generated by default as identity primary key,
  po_number text not null references public.purchase_orders(po_number) on delete cascade,
  line_no integer not null,
  material_id text not null references public.materials(id) on delete restrict,
  ordered_qty_milli bigint not null,
  received_qty_milli bigint not null default 0,
  unit_price_micros bigint not null,
  unit text not null,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text),
  constraint po_line_uidx unique (po_number, line_no)
);

create index po_line_material_idx on public.purchase_order_lines(material_id);

create table public.production_batches (
  id text primary key,
  production_date text not null,
  product_id text not null references public.products(id) on delete restrict,
  planned_qty_milli bigint not null,
  actual_produced_milli bigint not null default 0,
  rejected_milli bigint not null default 0,
  status text not null,
  operator text,
  wax_lot text,
  fragrance_lot text,
  container_lot text,
  unit_cost_snapshot_micros bigint,
  total_cost_snapshot_micros bigint,
  waste_cost_snapshot_micros bigint,
  completed_at text,
  notes text,
  created_at text not null default (current_timestamp::text),
  updated_at text not null default (current_timestamp::text)
);

create index batch_status_idx on public.production_batches(status);
create index batch_product_idx on public.production_batches(product_id);

create table public.stock_movements (
  id text primary key,
  occurred_on text not null,
  item_kind text not null,
  item_id text not null,
  movement_type text not null,
  quantity_milli bigint not null,
  unit_cost_micros bigint not null default 0,
  batch_id text references public.production_batches(id) on delete set null,
  po_number text references public.purchase_orders(po_number) on delete set null,
  lot_ref text,
  waste_event_id text,
  reason text,
  source text not null default 'app',
  created_at text not null default (current_timestamp::text)
);

create index movement_item_idx on public.stock_movements(item_kind, item_id);
create index movement_batch_idx on public.stock_movements(batch_id);
create index movement_po_idx on public.stock_movements(po_number);

create table public.waste_events (
  id text primary key,
  occurred_on text not null,
  batch_id text references public.production_batches(id) on delete set null,
  product_id text references public.products(id) on delete set null,
  material_id text not null references public.materials(id) on delete restrict,
  waste_type text not null,
  lot_ref text,
  quantity_milli bigint not null,
  unit text not null,
  unit_cost_snapshot_micros bigint not null,
  stock_movement_id text not null unique,
  notes text,
  created_at text not null default (current_timestamp::text)
);

create index waste_batch_idx on public.waste_events(batch_id);
create index waste_material_idx on public.waste_events(material_id);

create table public.audit_events (
  id text primary key,
  occurred_at text not null default (current_timestamp::text),
  actor text not null,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  before_json text,
  after_json text,
  effects_json text not null,
  idempotency_key text,
  source text not null default 'app'
);

create index audit_entity_idx on public.audit_events(entity_type, entity_id);
create index audit_occurred_idx on public.audit_events(occurred_at);
create unique index audit_idempotency_uidx on public.audit_events(idempotency_key);

create table public.idempotency_keys (
  key text primary key,
  action text not null,
  response_json text not null,
  created_at text not null default (current_timestamp::text)
);

create schema candle_private;
revoke all on schema candle_private from public, anon, authenticated;

create function candle_private.enforce_material_stock_nonnegative()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_balance bigint;
begin
  if new.source = 'app' and new.item_kind = 'material' and new.quantity_milli < 0 then
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('material:' || new.item_id, 0));
    select coalesce(sum(quantity_milli), 0)
      into current_balance
      from public.stock_movements
      where item_kind = 'material' and item_id = new.item_id;
    if current_balance + new.quantity_milli < 0 then
      raise exception using errcode = '23514', message = 'Material stock would become negative.';
    end if;
  end if;
  return new;
end;
$$;

create trigger app_material_stock_nonnegative
before insert on public.stock_movements
for each row execute function candle_private.enforce_material_stock_nonnegative();

create function candle_private.enforce_po_receipt_not_overposted()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  posted_quantity bigint;
  recorded_quantity bigint;
begin
  if new.source = 'app' and new.movement_type = 'purchase_receipt' then
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('po:' || coalesce(new.po_number, '') || ':' || new.item_id, 0));
    select coalesce(sum(quantity_milli), 0)
      into posted_quantity
      from public.stock_movements
      where movement_type = 'purchase_receipt'
        and po_number = new.po_number
        and item_id = new.item_id;
    select coalesce(sum(received_qty_milli), 0)
      into recorded_quantity
      from public.purchase_order_lines
      where po_number = new.po_number
        and material_id = new.item_id;
    if posted_quantity + new.quantity_milli > recorded_quantity then
      raise exception using errcode = '23514', message = 'Receipt would exceed the recorded PO quantity.';
    end if;
  end if;
  return new;
end;
$$;

create trigger app_po_receipt_not_overposted
before insert on public.stock_movements
for each row execute function candle_private.enforce_po_receipt_not_overposted();

do $$
declare
  relation_name text;
begin
  foreach relation_name in array array[
    'app_meta', 'settings', 'suppliers', 'materials', 'products', 'bom_items',
    'production_plans', 'production_plan_lines', 'purchase_orders',
    'purchase_order_lines', 'production_batches', 'stock_movements',
    'waste_events', 'audit_events', 'idempotency_keys'
  ] loop
    execute format('alter table public.%I enable row level security', relation_name);
    execute format('revoke all on table public.%I from anon, authenticated', relation_name);
    execute format('grant all on table public.%I to service_role', relation_name);
  end loop;
end;
$$;

revoke all on all sequences in schema public from anon, authenticated;
grant usage, select on all sequences in schema public to service_role;

alter default privileges for role postgres in schema public revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema public revoke all on sequences from anon, authenticated;
